using System;

void main()
{
	throw Exception("foo");
}
